chore(deps): bump exceptiongroup from 1.0.0 to 1.0.4 in /packages/ai (#1167)
Bumps [exceptiongroup](https://github.com/agronholm/exceptiongroup) from 1.0.0 to 1.0.4.
log</summary>
<p><em>Sourced from <a href="https://github.com/agronholm/exceptiongroup/blob/main/CHANGES.rst">exceptiongroup's changelog</a>.</em></p>
<blockquote>
<h1>Version history</h1>
<p>This library adheres to <code>Semantic Versioning 2.0 &lt;http://semver.org/&gt;</code>_.</p>
<p><strong>1.0.4</strong></p>
<ul>
<li>Fixed regression introduced in v1.0.3 where the code computing the suggestions would
assume that both the <code>obj</code> attribute of <code>AttributeError</code> is always available, even
though this is only true from Python 3.10 onwards
(<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/43">#43</a>; PR by Carl Friedrich Bolz-Tereick)</li>
</ul>
<p><strong>1.0.3</strong></p>
<ul>
<li>Fixed monkey patching breaking suggestions (on a <code>NameError</code> or <code>AttributeError</code>)
on Python 3.10 (<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/41">#41</a>; PR by Carl Friedrich Bolz-Tereick)</li>
</ul>
<p><strong>1.0.2</strong></p>
<ul>
<li>Updated type annotations to match the ones in <code>typeshed</code></li>
</ul>
<p><strong>1.0.1</strong></p>
<ul>
<li>Fixed formatted traceback missing exceptions beyond 2 nesting levels of
<code>__context__</code> or <code>__cause__</code></li>
</ul>
<p><strong>1.0.0</strong></p>
<ul>
<li>Fixed
<code>AttributeError: 'PatchedTracebackException' object has no attribute '__cause__'</code>
on Python 3.10 (only) when a traceback is printed from an exception where an exception
group is set as the cause (<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/33">#33</a>)</li>
<li>Fixed a loop in exception groups being rendered incorrectly (<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/35">#35</a>)</li>
<li>Fixed the patched formatting functions (<code>format_exception()</code>etc.) not passing the
<code>compact=True</code> flag on Python 3.10 like the original functions do</li>
</ul>
<p><strong>1.0.0rc9</strong></p>
<ul>
<li>Added custom versions of several <code>traceback</code>  functions that work with exception
groups even if monkey patching was disabled or blocked</li>
</ul>
<p><strong>1.0.0rc8</strong></p>
<ul>
<li>Don't monkey patch anything if <code>sys.excepthook</code> has been altered</li>
<li>Fixed formatting of <code>SyntaxError</code> in the monkey patched
<code>TracebackException.format_exception_only()</code> method</li>
</ul>
<p><strong>1.0.0rc7</strong></p>
<ul>
<li><strong>BACKWARDS INCOMPATIBLE</strong> Changed <code>catch()</code> to not wrap an exception in an</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/6d1bd7dca2edf168d50945ee1cd6479346bc1679"><code>6d1bd7d</code></a> Added the release version</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/185f16cafd3cd25ed794d436310676a6f0e8f121"><code>185f16c</code></a> Added news item for PR <a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/44">#44</a></li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/4853c83f9c44e67b351185350562b601bfbd58b5"><code>4853c83</code></a> AttributeError instances might not have a .obj (<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/44">#44</a>)</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/ac97f0fdb37943036174d1ccbd9cd0460082018e"><code>ac97f0f</code></a> Added the release version</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/de2b4b3098cfeb8221799243f3d3c82494d1ceba"><code>de2b4b3</code></a> Added news item on PR <a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/42">#42</a></li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/ebb458268c00ba7e98333d7dda7ade300e7426d6"><code>ebb4582</code></a> Backported the pure Python suggestion code from 3.12 (<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/42">#42</a>)</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/5bf369206f39d4c33516bb8010ef51b59ffa6ca9"><code>5bf3692</code></a> Added the release version</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/cbac14e8889e5f49cb6fb61d977e59e625ac2598"><code>cbac14e</code></a> Updated type annotations to match those in typeshed (<a href="https://github-redirect.dependabot.com/agronholm/exceptiongroup/issues/40">#40</a>)</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/21676396d2814076aee4e01a6e61a66cfd5e68db"><code>2167639</code></a> Updated pre-commit modules</li>
<li><a href="https://github.com/agronholm/exceptiongroup/commit/996e81f5f97dc9542ee332c5f322d95ff7152584"><code>996e81f</code></a> Added the release version</li>
<li>Additional commits viewable in <a href="https://github.com/agronholm/exceptiongroup/compare/1.0.0...1.0.4">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=exceptiongroup&package-manager=pip&previous-version=1.0.0&new-version=1.0.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>